### ISSUE TITLE
change the order of announcements while navigating the ring to abbreviation / time / date or country / city / time / date

### ISSUE THREAD

**Issue by Adriani90** [munawarb/NVDA-Time-Zoner#6]
Steps to reproduce:
1. Navigate the ring after adding some time zones to it

Actual behavior: NVDA reports time / date / abbreviation or time / date / continent / city
expected behavior: The continent is for the most users of this addon not really useful informatoin. Thus I would expect following order for much more efficiency:
* Country / city / time / date or
* Abbreviation / time / date
And the continent should not be announced while navigating the ring.

**Comment by munawarb** [comment]
Hi @Adriani90,
This is a great suggestion. I think the option with the most flexibility here is to allow the user to enter their desired format string. The interface can provide an edit box that will show the current string, along with buttons to insert special variables. It will result in a string such as:
```python
{country}:{city} {time} {date}
```
or (the default):
```python
{time}, {date} ({shortTimezone})
```

What do you think? This way you can customize the readout to your liking.

**Comment by Adriani90** [comment]
Sounds good, but you should implement an error message, if the brackets are deleted. Otherwise it is hard for beginners. This needs to be documented properly in the readme. Additionally,you could add a checkable list with checkboxes for the elements (date, time, country, city, abbreviation). The user can uncheck elements to increase efficiency. 

Von meinem iPhone gesendet
